name: mu_super_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_usage: ^4.0.1
  flutter_overlay_window: ^0.5.0
  shared_preferences: ^2.2.0
  permission_handler: ^11.0.0
  adhan_dart: ^1.2.0
  geolocator: ^14.0.2
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  fl_chart: ^0.65.0
  local_auth: ^2.1.8
  crypto: ^3.0.3
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
